<a href="https://colab.research.google.com/github/rigole/TensorFlow-/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Tensors Using TensorFlow

## Introduction to Tensors

In [ ]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Let's Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (vector with more than 1 dimension)
matrix = tf.constant([[45, 54],
                     [14, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[45, 54],
       [14, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
 # Create another matrix
 another_matrix = tf.constant([[10., 7.],
                               [3., 2.],
                               [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
 # number of dimension

 another_matrix.ndim

2

In [ ]:
# Let's create a tensor

tensor = tf.constant([[[1, 2, 3,],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])



<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>